# Generated by Django 2.2.6 on 2019-10-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='markcoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xcord', models.FloatField(verbose_name='X coord')),
                ('ycord', models.FloatField(verbose_name='Y coord')),
            ],
        ),
    ]
