# Generated by Django 2.2.6 on 2019-10-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0002_markcoord_timecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='markcoord',
            name='city',
            field=models.CharField(choices=[('TM', 'Tumen'), ('EK', 'Ekaterinburg')], default='TM', max_length=200, verbose_name='City'),
        ),
    ]
