# Generated by Django 2.2.6 on 2019-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0003_markcoord_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markcoord',
            name='city',
            field=models.CharField(choices=[('TM', 'Tumen'), ('EK', 'Ekaterinburg')], default=('TM', 'Tumen'), max_length=200, verbose_name='City'),
        ),
    ]
