# Generated by Django 2.2.6 on 2019-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_auto_20191014_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='markcoord',
            name='hate_point',
            field=models.IntegerField(default=0, verbose_name='Hate Points'),
        ),
        migrations.AddField(
            model_name='markcoord',
            name='like_point',
            field=models.IntegerField(default=0, verbose_name='Like Points'),
        ),
    ]
